project_id = "hoxcnuzfqwcissykayqa"

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.lumen-agent]
verify_jwt = false

[functions.essentia-concierge]
verify_jwt = false

[functions.miguel-agent]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = true

[functions.list-stripe-coupons]
verify_jwt = true

[functions.create-stripe-coupon]
verify_jwt = true

[functions.nello-concierge]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-pdf-email]
verify_jwt = true

[functions.miguel-codigo-essencia]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.send-journey-reminder]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.auto-journey-reminders]
verify_jwt = false

[functions.verify-checkout]
verify_jwt = false

[functions.flow-mentor]
verify_jwt = true

[functions.flow-checkout]
verify_jwt = true

[functions.flow-check-subscription]
verify_jwt = true

[functions.flow-customer-portal]
verify_jwt = true
