
-- First, delete existing questions for linguagens_amor tests
DELETE FROM test_questions 
WHERE test_id IN (SELECT id FROM tests WHERE type = 'linguagens_amor');

-- Insert new questions for Portuguese (pt) test
INSERT INTO test_questions (test_id, question_number, question_text, options, language)
SELECT t.id, q.question_number, q.question_text, q.options::jsonb, 'pt'
FROM tests t
CROSS JOIN (VALUES
  (1, 'Você acabou de receber uma notícia difícil no trabalho. O que mais te ajudaria?', '[{"label": "Alguém sentar ao seu lado em silêncio, apenas fazendo companhia", "value": "presenca_ativa"}, {"label": "Receber uma massagem nos ombros para aliviar a tensão", "value": "conexao_fisica"}, {"label": "Ouvir \"Eu acredito em você, vai superar isso\"", "value": "expressao_verbal"}, {"label": "Alguém preparar um chá ou organizar algo para você", "value": "cuidado_pratico"}, {"label": "Receber uma mensagem ou cartão de apoio inesperado", "value": "gestos_simbolicos"}]'),
  (2, 'Após uma briga com alguém próximo, o que te faz sentir que a paz foi restaurada?', '[{"label": "A pessoa resolver algo que estava te incomodando", "value": "cuidado_pratico"}, {"label": "Um abraço demorado sem precisar de palavras", "value": "conexao_fisica"}, {"label": "Receber um pedido de desculpas sincero e elaborado", "value": "expressao_verbal"}, {"label": "A pessoa aparecer com algo especial para vocês dois", "value": "gestos_simbolicos"}, {"label": "Passarem um tempo juntos fazendo algo relaxante", "value": "presenca_ativa"}]'),
  (3, 'Em um dia de ansiedade, qual atitude de alguém querido te acalmaria mais?', '[{"label": "Ficar de mãos dadas enquanto você respira", "value": "conexao_fisica"}, {"label": "Dizer palavras tranquilizadoras com calma", "value": "expressao_verbal"}, {"label": "Trazer algo que você gosta para te distrair", "value": "gestos_simbolicos"}, {"label": "Cuidar de alguma tarefa pendente para tirar da sua cabeça", "value": "cuidado_pratico"}, {"label": "Simplesmente ficar por perto, disponível", "value": "presenca_ativa"}]'),
  (4, 'Quando você está doente, o que mais te faz sentir cuidado(a)?', '[{"label": "Alguém passar o dia ao seu lado, mesmo sem fazer nada especial", "value": "presenca_ativa"}, {"label": "Ouvir mensagens de \"melhoras\" e preocupação genuína", "value": "expressao_verbal"}, {"label": "Receber um mimo especial como flores ou algo que você adora", "value": "gestos_simbolicos"}, {"label": "Alguém preparar uma sopa ou organizar seus remédios", "value": "cuidado_pratico"}, {"label": "Receber cafuné e carinho físico enquanto descansa", "value": "conexao_fisica"}]'),
  (5, 'Após um fracasso pessoal, qual reação te faria sentir mais apoiado(a)?', '[{"label": "Alguém pesquisar soluções ou alternativas para você", "value": "cuidado_pratico"}, {"label": "Ouvir \"Isso não diminui quem você é\"", "value": "expressao_verbal"}, {"label": "Receber um presente simbólico de encorajamento", "value": "gestos_simbolicos"}, {"label": "Um abraço forte e prolongado", "value": "conexao_fisica"}, {"label": "A pessoa reservar tempo para estar com você", "value": "presenca_ativa"}]'),
  (6, 'Quando está passando por luto ou perda, o que mais te conforta?', '[{"label": "Alguém cuidar de questões práticas que você não consegue enfrentar", "value": "cuidado_pratico"}, {"label": "Presença silenciosa, apenas estando ali", "value": "presenca_ativa"}, {"label": "Toque gentil como segurar sua mão ou abraço", "value": "conexao_fisica"}, {"label": "Palavras de conforto e memórias compartilhadas", "value": "expressao_verbal"}, {"label": "Receber algo significativo em memória do momento", "value": "gestos_simbolicos"}]'),
  (7, 'Você conseguiu uma promoção no trabalho. Qual reação te deixaria mais feliz?', '[{"label": "A pessoa organizar uma comemoração surpresa", "value": "gestos_simbolicos"}, {"label": "Ouvir um discurso sincero sobre seu mérito", "value": "expressao_verbal"}, {"label": "Receber um abraço apertado e efusivo", "value": "conexao_fisica"}, {"label": "Alguém se disponibilizar para celebrar como você quiser", "value": "presenca_ativa"}, {"label": "A pessoa resolver algo prático para facilitar sua nova rotina", "value": "cuidado_pratico"}]'),
  (8, 'No seu aniversário, o que te faz sentir mais especial?', '[{"label": "Alguém dedicar o dia inteiro para estar com você", "value": "presenca_ativa"}, {"label": "Receber um presente bem pensado que mostra atenção", "value": "gestos_simbolicos"}, {"label": "Ouvir declarações e agradecimentos sinceros", "value": "expressao_verbal"}, {"label": "Abraços, beijos e muito contato físico", "value": "conexao_fisica"}, {"label": "Alguém preparar tudo para você não se preocupar com nada", "value": "cuidado_pratico"}]'),
  (9, 'Ao completar um projeto importante, como prefere ser reconhecido(a)?', '[{"label": "Um elogio público ou privado detalhado", "value": "expressao_verbal"}, {"label": "Um presente ou símbolo do feito", "value": "gestos_simbolicos"}, {"label": "Um high-five, tapinha nas costas ou abraço", "value": "conexao_fisica"}, {"label": "Alguém querer saber os detalhes e ouvir sobre a experiência", "value": "presenca_ativa"}, {"label": "Ajuda prática com o próximo passo", "value": "cuidado_pratico"}]'),
  (10, 'Em uma conquista acadêmica ou profissional, o que mais te emociona?', '[{"label": "Alguém fazer algo especial para marcar o momento", "value": "gestos_simbolicos"}, {"label": "Ouvir o quanto estão orgulhosos de você", "value": "expressao_verbal"}, {"label": "Receber abraços calorosos de celebração", "value": "conexao_fisica"}, {"label": "A pessoa pausar tudo para celebrar com você", "value": "presenca_ativa"}, {"label": "Ajuda para organizar a próxima fase", "value": "cuidado_pratico"}]'),
  (11, 'Quando atinge uma meta fitness ou de saúde, qual reação te motiva mais?', '[{"label": "Alguém te acompanhar nessa jornada", "value": "presenca_ativa"}, {"label": "Elogios específicos sobre seu esforço e resultado", "value": "expressao_verbal"}, {"label": "Um mimo ou recompensa simbólica", "value": "gestos_simbolicos"}, {"label": "Massagem ou toque celebratório", "value": "conexao_fisica"}, {"label": "Ajuda para manter o novo hábito", "value": "cuidado_pratico"}]'),
  (12, 'Ao receber boas notícias inesperadas, o que você mais quer?', '[{"label": "Compartilhar a novidade com tempo e atenção de alguém", "value": "presenca_ativa"}, {"label": "Expressar sua alegria em palavras com alguém", "value": "expressao_verbal"}, {"label": "Pular, abraçar e expressar fisicamente", "value": "conexao_fisica"}, {"label": "Receber ou dar algo para marcar o momento", "value": "gestos_simbolicos"}, {"label": "Alguém ajudar a planejar os próximos passos", "value": "cuidado_pratico"}]'),
  (13, 'Em um domingo comum, o que te faz sentir mais conectado(a) a alguém?', '[{"label": "Fazer tarefas domésticas juntos", "value": "cuidado_pratico"}, {"label": "Conversar profundamente sobre qualquer assunto", "value": "expressao_verbal"}, {"label": "Passar o dia lado a lado, mesmo em silêncio", "value": "presenca_ativa"}, {"label": "Trocar carinhos no sofá assistindo algo", "value": "conexao_fisica"}, {"label": "Receber ou preparar algo especial para o outro", "value": "gestos_simbolicos"}]'),
  (14, 'Chegando do trabalho cansado(a), o que mais te acolhe?', '[{"label": "Encontrar a casa arrumada ou o jantar pronto", "value": "cuidado_pratico"}, {"label": "Ouvir \"Como foi seu dia?\" com interesse genuíno", "value": "expressao_verbal"}, {"label": "Um abraço demorado na porta", "value": "conexao_fisica"}, {"label": "Ter companhia enquanto descansa", "value": "presenca_ativa"}, {"label": "Uma pequena surpresa como um bilhete ou doce favorito", "value": "gestos_simbolicos"}]'),
  (15, 'Durante uma refeição em família, o que mais te toca?', '[{"label": "Conversas animadas e conexão verbal", "value": "expressao_verbal"}, {"label": "Alguém ter preparado seu prato favorito", "value": "cuidado_pratico"}, {"label": "Sentar próximo, com contato físico casual", "value": "conexao_fisica"}, {"label": "Todos estarem presentes e focados", "value": "presenca_ativa"}, {"label": "Pequenos rituais como brindes ou tradições", "value": "gestos_simbolicos"}]'),
  (16, 'Em uma viagem com alguém especial, o que torna a experiência memorável?', '[{"label": "Conversas profundas durante o trajeto", "value": "expressao_verbal"}, {"label": "Alguém cuidar da logística e organização", "value": "cuidado_pratico"}, {"label": "Explorar lugares juntos, lado a lado", "value": "presenca_ativa"}, {"label": "Momentos de intimidade física", "value": "conexao_fisica"}, {"label": "Souvenirs e lembranças simbólicas", "value": "gestos_simbolicos"}]'),
  (17, 'No fim de um dia estressante, o que mais te relaxa?', '[{"label": "Desabafar e ser ouvido(a) com atenção", "value": "expressao_verbal"}, {"label": "Alguém assumir suas responsabilidades por uma noite", "value": "cuidado_pratico"}, {"label": "Receber carinho físico como massagem ou cafuné", "value": "conexao_fisica"}, {"label": "Companhia silenciosa e reconfortante", "value": "presenca_ativa"}, {"label": "Uma surpresa simples para alegrar", "value": "gestos_simbolicos"}]'),
  (18, 'Em uma manhã de folga, o que te faz sentir amado(a)?', '[{"label": "Café na cama ou algo preparado com carinho", "value": "cuidado_pratico"}, {"label": "Acordar com beijos e abraços", "value": "conexao_fisica"}, {"label": "Ouvir \"Bom dia\" de forma carinhosa e atenciosa", "value": "expressao_verbal"}, {"label": "A pessoa querer passar a manhã ao seu lado", "value": "presenca_ativa"}, {"label": "Encontrar um bilhete ou pequena surpresa", "value": "gestos_simbolicos"}]'),
  (19, 'O que mais te faz confiar que alguém te ama?', '[{"label": "Declarações verbais frequentes de amor", "value": "expressao_verbal"}, {"label": "Ações práticas do dia a dia que facilitam sua vida", "value": "cuidado_pratico"}, {"label": "Presentes e gestos simbólicos inesperados", "value": "gestos_simbolicos"}, {"label": "Toque frequente e busca por proximidade física", "value": "conexao_fisica"}, {"label": "Tempo de qualidade dedicado a você", "value": "presenca_ativa"}]'),
  (20, 'Em um relacionamento de longa data, o que mantém a chama acesa?', '[{"label": "Surpresas românticas e gestos simbólicos", "value": "gestos_simbolicos"}, {"label": "Conversas profundas e conexão verbal", "value": "expressao_verbal"}, {"label": "Intimidade física e carinhos frequentes", "value": "conexao_fisica"}, {"label": "Momentos de presença plena juntos", "value": "presenca_ativa"}, {"label": "Cuidado mútuo nas pequenas coisas", "value": "cuidado_pratico"}]'),
  (21, 'Quando sente que está se distanciando de alguém, o que te reaproxima?', '[{"label": "Uma conversa honesta sobre sentimentos", "value": "expressao_verbal"}, {"label": "Um presente ou gesto significativo de reconciliação", "value": "gestos_simbolicos"}, {"label": "Abraços e restauração do contato físico", "value": "conexao_fisica"}, {"label": "Passarem tempo de qualidade juntos", "value": "presenca_ativa"}, {"label": "A pessoa tomar atitudes práticas para resolver problemas", "value": "cuidado_pratico"}]'),
  (22, 'O que te faz sentir negligenciado(a) em um relacionamento?', '[{"label": "Falta de palavras de afirmação e elogios", "value": "expressao_verbal"}, {"label": "Ausência de presentes ou gestos simbólicos", "value": "gestos_simbolicos"}, {"label": "Pouco contato físico e intimidade", "value": "conexao_fisica"}, {"label": "A pessoa nunca ter tempo para você", "value": "presenca_ativa"}, {"label": "Não ajudar nas tarefas e responsabilidades", "value": "cuidado_pratico"}]'),
  (23, 'Em uma amizade verdadeira, o que você mais valoriza?', '[{"label": "Poder contar tudo e ser ouvido(a)", "value": "expressao_verbal"}, {"label": "Ajuda mútua em momentos práticos", "value": "cuidado_pratico"}, {"label": "Lembranças e gestos que mostram que pensam em você", "value": "gestos_simbolicos"}, {"label": "Abraços e demonstrações físicas de afeto", "value": "conexao_fisica"}, {"label": "Passarem tempo juntos regularmente", "value": "presenca_ativa"}]'),
  (24, 'Ao conhecer alguém novo, o que te faz sentir conexão imediata?', '[{"label": "Conversa fluida e interessante", "value": "expressao_verbal"}, {"label": "A pessoa se oferecer para ajudar em algo", "value": "cuidado_pratico"}, {"label": "Troca de pequenas gentilezas ou presentes", "value": "gestos_simbolicos"}, {"label": "Contato físico natural como aperto de mão caloroso", "value": "conexao_fisica"}, {"label": "Vontade de passar mais tempo juntos", "value": "presenca_ativa"}]'),
  (25, 'Pensando em sua infância, quando você se sentia mais amado(a)?', '[{"label": "Quando ouviam suas histórias com atenção", "value": "presenca_ativa"}, {"label": "Quando recebiam elogios e incentivo verbal", "value": "expressao_verbal"}, {"label": "Quando ganhavam presentes significativos", "value": "gestos_simbolicos"}, {"label": "Quando alguém cuidava de suas necessidades práticas", "value": "cuidado_pratico"}, {"label": "Quando recebiam abraços e carinho físico", "value": "conexao_fisica"}]'),
  (26, 'Com sua família hoje, o que mais te faz sentir pertencimento?', '[{"label": "Reuniões onde todos estão presentes", "value": "presenca_ativa"}, {"label": "Conversas e ligações frequentes", "value": "expressao_verbal"}, {"label": "Tradições e rituais familiares", "value": "gestos_simbolicos"}, {"label": "Apoio mútuo em questões práticas", "value": "cuidado_pratico"}, {"label": "Demonstrações físicas de afeto", "value": "conexao_fisica"}]'),
  (27, 'O que você mais sente falta em relação à sua família quando está longe?', '[{"label": "Das conversas e da voz das pessoas", "value": "expressao_verbal"}, {"label": "Da ajuda prática e do suporte mútuo", "value": "cuidado_pratico"}, {"label": "Dos abraços e do contato físico", "value": "conexao_fisica"}, {"label": "Das tradições e momentos especiais", "value": "gestos_simbolicos"}, {"label": "De simplesmente estar junto", "value": "presenca_ativa"}]'),
  (28, 'Qual memória afetiva familiar é mais forte para você?', '[{"label": "Palavras de encorajamento e amor", "value": "expressao_verbal"}, {"label": "Alguém cuidando de você quando precisou", "value": "cuidado_pratico"}, {"label": "Presentes ou objetos que guarda até hoje", "value": "gestos_simbolicos"}, {"label": "Abraços e colo em momentos importantes", "value": "conexao_fisica"}, {"label": "Momentos de presença e atenção plena", "value": "presenca_ativa"}]'),
  (29, 'Como você costuma demonstrar amor para pessoas importantes?', '[{"label": "Com palavras de afirmação e elogios", "value": "expressao_verbal"}, {"label": "Fazendo coisas práticas para facilitar a vida delas", "value": "cuidado_pratico"}, {"label": "Dando presentes pensados e significativos", "value": "gestos_simbolicos"}, {"label": "Com abraços, carinhos e toque frequente", "value": "conexao_fisica"}, {"label": "Dedicando tempo de qualidade exclusivo", "value": "presenca_ativa"}]'),
  (30, 'Se pudesse pedir uma coisa para se sentir mais amado(a), seria:', '[{"label": "Ouvir mais frequentemente o quanto sou importante", "value": "expressao_verbal"}, {"label": "Receber mais ajuda nas tarefas do dia a dia", "value": "cuidado_pratico"}, {"label": "Receber mais surpresas e gestos simbólicos", "value": "gestos_simbolicos"}, {"label": "Mais carinho físico e proximidade", "value": "conexao_fisica"}, {"label": "Mais tempo de qualidade e atenção plena", "value": "presenca_ativa"}]')
) AS q(question_number, question_text, options)
WHERE t.type = 'linguagens_amor' AND t.language = 'pt';

-- Insert new questions for English (en) test
INSERT INTO test_questions (test_id, question_number, question_text, options, language)
SELECT t.id, q.question_number, q.question_text, q.options::jsonb, 'en'
FROM tests t
CROSS JOIN (VALUES
  (1, 'You just received difficult news at work. What would help you the most?', '[{"label": "Someone sitting beside you in silence, just keeping you company", "value": "presenca_ativa"}, {"label": "Receiving a shoulder massage to relieve tension", "value": "conexao_fisica"}, {"label": "Hearing \"I believe in you, you will overcome this\"", "value": "expressao_verbal"}, {"label": "Someone preparing tea or organizing something for you", "value": "cuidado_pratico"}, {"label": "Receiving an unexpected message or card of support", "value": "gestos_simbolicos"}]'),
  (2, 'After an argument with someone close, what makes you feel peace has been restored?', '[{"label": "The person resolving something that was bothering you", "value": "cuidado_pratico"}, {"label": "A long hug without needing words", "value": "conexao_fisica"}, {"label": "Receiving a sincere and elaborate apology", "value": "expressao_verbal"}, {"label": "The person showing up with something special for both of you", "value": "gestos_simbolicos"}, {"label": "Spending relaxing time together", "value": "presenca_ativa"}]'),
  (3, 'On an anxious day, what action from a loved one would calm you the most?', '[{"label": "Holding hands while you breathe", "value": "conexao_fisica"}, {"label": "Saying calming words gently", "value": "expressao_verbal"}, {"label": "Bringing something you like to distract you", "value": "gestos_simbolicos"}, {"label": "Taking care of a pending task to clear your mind", "value": "cuidado_pratico"}, {"label": "Simply staying nearby, available", "value": "presenca_ativa"}]'),
  (4, 'When you are sick, what makes you feel most cared for?', '[{"label": "Someone spending the day by your side, even without doing anything special", "value": "presenca_ativa"}, {"label": "Hearing \"get well\" messages and genuine concern", "value": "expressao_verbal"}, {"label": "Receiving a special treat like flowers or something you love", "value": "gestos_simbolicos"}, {"label": "Someone preparing soup or organizing your medicine", "value": "cuidado_pratico"}, {"label": "Receiving physical affection and caresses while resting", "value": "conexao_fisica"}]'),
  (5, 'After a personal failure, what reaction would make you feel most supported?', '[{"label": "Someone researching solutions or alternatives for you", "value": "cuidado_pratico"}, {"label": "Hearing \"This doesn''t diminish who you are\"", "value": "expressao_verbal"}, {"label": "Receiving a symbolic gift of encouragement", "value": "gestos_simbolicos"}, {"label": "A strong and prolonged hug", "value": "conexao_fisica"}, {"label": "The person setting aside time to be with you", "value": "presenca_ativa"}]'),
  (6, 'When going through grief or loss, what comforts you the most?', '[{"label": "Someone taking care of practical matters you cannot face", "value": "cuidado_pratico"}, {"label": "Silent presence, just being there", "value": "presenca_ativa"}, {"label": "Gentle touch like holding your hand or a hug", "value": "conexao_fisica"}, {"label": "Words of comfort and shared memories", "value": "expressao_verbal"}, {"label": "Receiving something meaningful in memory of the moment", "value": "gestos_simbolicos"}]'),
  (7, 'You got a promotion at work. What reaction would make you happiest?', '[{"label": "The person organizing a surprise celebration", "value": "gestos_simbolicos"}, {"label": "Hearing a sincere speech about your merit", "value": "expressao_verbal"}, {"label": "Receiving a tight and effusive hug", "value": "conexao_fisica"}, {"label": "Someone making themselves available to celebrate however you want", "value": "presenca_ativa"}, {"label": "The person handling something practical to ease your new routine", "value": "cuidado_pratico"}]'),
  (8, 'On your birthday, what makes you feel most special?', '[{"label": "Someone dedicating the whole day to be with you", "value": "presenca_ativa"}, {"label": "Receiving a well-thought gift that shows attention", "value": "gestos_simbolicos"}, {"label": "Hearing sincere declarations and thanks", "value": "expressao_verbal"}, {"label": "Hugs, kisses and lots of physical contact", "value": "conexao_fisica"}, {"label": "Someone preparing everything so you don''t have to worry about anything", "value": "cuidado_pratico"}]'),
  (9, 'When completing an important project, how do you prefer to be recognized?', '[{"label": "A detailed public or private compliment", "value": "expressao_verbal"}, {"label": "A gift or symbol of achievement", "value": "gestos_simbolicos"}, {"label": "A high-five, pat on the back or hug", "value": "conexao_fisica"}, {"label": "Someone wanting to hear the details about the experience", "value": "presenca_ativa"}, {"label": "Practical help with the next step", "value": "cuidado_pratico"}]'),
  (10, 'In an academic or professional achievement, what moves you the most?', '[{"label": "Someone doing something special to mark the moment", "value": "gestos_simbolicos"}, {"label": "Hearing how proud they are of you", "value": "expressao_verbal"}, {"label": "Receiving warm celebratory hugs", "value": "conexao_fisica"}, {"label": "The person pausing everything to celebrate with you", "value": "presenca_ativa"}, {"label": "Help organizing the next phase", "value": "cuidado_pratico"}]'),
  (11, 'When you reach a fitness or health goal, what reaction motivates you most?', '[{"label": "Someone accompanying you on this journey", "value": "presenca_ativa"}, {"label": "Specific compliments about your effort and results", "value": "expressao_verbal"}, {"label": "A treat or symbolic reward", "value": "gestos_simbolicos"}, {"label": "Massage or celebratory touch", "value": "conexao_fisica"}, {"label": "Help maintaining the new habit", "value": "cuidado_pratico"}]'),
  (12, 'When receiving unexpected good news, what do you want most?', '[{"label": "Sharing the news with someone''s time and attention", "value": "presenca_ativa"}, {"label": "Expressing your joy in words with someone", "value": "expressao_verbal"}, {"label": "Jumping, hugging and expressing physically", "value": "conexao_fisica"}, {"label": "Receiving or giving something to mark the moment", "value": "gestos_simbolicos"}, {"label": "Someone helping plan the next steps", "value": "cuidado_pratico"}]'),
  (13, 'On a regular Sunday, what makes you feel most connected to someone?', '[{"label": "Doing household chores together", "value": "cuidado_pratico"}, {"label": "Having deep conversation about any subject", "value": "expressao_verbal"}, {"label": "Spending the day side by side, even in silence", "value": "presenca_ativa"}, {"label": "Exchanging caresses on the couch watching something", "value": "conexao_fisica"}, {"label": "Receiving or preparing something special for each other", "value": "gestos_simbolicos"}]'),
  (14, 'Coming home tired from work, what welcomes you the most?', '[{"label": "Finding the house tidy or dinner ready", "value": "cuidado_pratico"}, {"label": "Hearing \"How was your day?\" with genuine interest", "value": "expressao_verbal"}, {"label": "A long hug at the door", "value": "conexao_fisica"}, {"label": "Having company while you rest", "value": "presenca_ativa"}, {"label": "A small surprise like a note or favorite treat", "value": "gestos_simbolicos"}]'),
  (15, 'During a family meal, what touches you the most?', '[{"label": "Lively conversations and verbal connection", "value": "expressao_verbal"}, {"label": "Someone having prepared your favorite dish", "value": "cuidado_pratico"}, {"label": "Sitting close, with casual physical contact", "value": "conexao_fisica"}, {"label": "Everyone being present and focused", "value": "presenca_ativa"}, {"label": "Small rituals like toasts or traditions", "value": "gestos_simbolicos"}]'),
  (16, 'On a trip with someone special, what makes the experience memorable?', '[{"label": "Deep conversations during the journey", "value": "expressao_verbal"}, {"label": "Someone taking care of logistics and organization", "value": "cuidado_pratico"}, {"label": "Exploring places together, side by side", "value": "presenca_ativa"}, {"label": "Moments of physical intimacy", "value": "conexao_fisica"}, {"label": "Souvenirs and symbolic keepsakes", "value": "gestos_simbolicos"}]'),
  (17, 'At the end of a stressful day, what relaxes you the most?', '[{"label": "Venting and being listened to with attention", "value": "expressao_verbal"}, {"label": "Someone taking over your responsibilities for one night", "value": "cuidado_pratico"}, {"label": "Receiving physical affection like massage or caresses", "value": "conexao_fisica"}, {"label": "Silent and comforting company", "value": "presenca_ativa"}, {"label": "A simple surprise to cheer you up", "value": "gestos_simbolicos"}]'),
  (18, 'On a morning off, what makes you feel loved?', '[{"label": "Breakfast in bed or something prepared with care", "value": "cuidado_pratico"}, {"label": "Waking up with kisses and hugs", "value": "conexao_fisica"}, {"label": "Hearing \"Good morning\" in an affectionate and attentive way", "value": "expressao_verbal"}, {"label": "The person wanting to spend the morning by your side", "value": "presenca_ativa"}, {"label": "Finding a note or small surprise", "value": "gestos_simbolicos"}]'),
  (19, 'What makes you most confident that someone loves you?', '[{"label": "Frequent verbal declarations of love", "value": "expressao_verbal"}, {"label": "Daily practical actions that make your life easier", "value": "cuidado_pratico"}, {"label": "Unexpected gifts and symbolic gestures", "value": "gestos_simbolicos"}, {"label": "Frequent touch and seeking physical proximity", "value": "conexao_fisica"}, {"label": "Quality time dedicated to you", "value": "presenca_ativa"}]'),
  (20, 'In a long-term relationship, what keeps the flame alive?', '[{"label": "Romantic surprises and symbolic gestures", "value": "gestos_simbolicos"}, {"label": "Deep conversations and verbal connection", "value": "expressao_verbal"}, {"label": "Physical intimacy and frequent caresses", "value": "conexao_fisica"}, {"label": "Moments of full presence together", "value": "presenca_ativa"}, {"label": "Mutual care in little things", "value": "cuidado_pratico"}]'),
  (21, 'When you feel you are drifting apart from someone, what brings you closer?', '[{"label": "An honest conversation about feelings", "value": "expressao_verbal"}, {"label": "A gift or meaningful gesture of reconciliation", "value": "gestos_simbolicos"}, {"label": "Hugs and restoration of physical contact", "value": "conexao_fisica"}, {"label": "Spending quality time together", "value": "presenca_ativa"}, {"label": "The person taking practical actions to solve problems", "value": "cuidado_pratico"}]'),
  (22, 'What makes you feel neglected in a relationship?', '[{"label": "Lack of words of affirmation and compliments", "value": "expressao_verbal"}, {"label": "Absence of gifts or symbolic gestures", "value": "gestos_simbolicos"}, {"label": "Little physical contact and intimacy", "value": "conexao_fisica"}, {"label": "The person never having time for you", "value": "presenca_ativa"}, {"label": "Not helping with tasks and responsibilities", "value": "cuidado_pratico"}]'),
  (23, 'In a true friendship, what do you value most?', '[{"label": "Being able to share everything and be heard", "value": "expressao_verbal"}, {"label": "Mutual help in practical moments", "value": "cuidado_pratico"}, {"label": "Remembrances and gestures showing they think of you", "value": "gestos_simbolicos"}, {"label": "Hugs and physical demonstrations of affection", "value": "conexao_fisica"}, {"label": "Spending time together regularly", "value": "presenca_ativa"}]'),
  (24, 'When meeting someone new, what makes you feel an immediate connection?', '[{"label": "Fluid and interesting conversation", "value": "expressao_verbal"}, {"label": "The person offering to help with something", "value": "cuidado_pratico"}, {"label": "Exchange of small courtesies or gifts", "value": "gestos_simbolicos"}, {"label": "Natural physical contact like a warm handshake", "value": "conexao_fisica"}, {"label": "Wanting to spend more time together", "value": "presenca_ativa"}]'),
  (25, 'Thinking about your childhood, when did you feel most loved?', '[{"label": "When they listened to your stories with attention", "value": "presenca_ativa"}, {"label": "When you received compliments and verbal encouragement", "value": "expressao_verbal"}, {"label": "When you received meaningful gifts", "value": "gestos_simbolicos"}, {"label": "When someone took care of your practical needs", "value": "cuidado_pratico"}, {"label": "When you received hugs and physical affection", "value": "conexao_fisica"}]'),
  (26, 'With your family today, what makes you feel most belonging?', '[{"label": "Gatherings where everyone is present", "value": "presenca_ativa"}, {"label": "Frequent conversations and calls", "value": "expressao_verbal"}, {"label": "Family traditions and rituals", "value": "gestos_simbolicos"}, {"label": "Mutual support in practical matters", "value": "cuidado_pratico"}, {"label": "Physical demonstrations of affection", "value": "conexao_fisica"}]'),
  (27, 'What do you miss most about your family when you are away?', '[{"label": "The conversations and people''s voices", "value": "expressao_verbal"}, {"label": "The practical help and mutual support", "value": "cuidado_pratico"}, {"label": "The hugs and physical contact", "value": "conexao_fisica"}, {"label": "The traditions and special moments", "value": "gestos_simbolicos"}, {"label": "Simply being together", "value": "presenca_ativa"}]'),
  (28, 'Which family affective memory is strongest for you?', '[{"label": "Words of encouragement and love", "value": "expressao_verbal"}, {"label": "Someone taking care of you when you needed it", "value": "cuidado_pratico"}, {"label": "Gifts or objects you still keep today", "value": "gestos_simbolicos"}, {"label": "Hugs and lap in important moments", "value": "conexao_fisica"}, {"label": "Moments of presence and full attention", "value": "presenca_ativa"}]'),
  (29, 'How do you usually show love to important people?', '[{"label": "With words of affirmation and compliments", "value": "expressao_verbal"}, {"label": "Doing practical things to make their lives easier", "value": "cuidado_pratico"}, {"label": "Giving thoughtful and meaningful gifts", "value": "gestos_simbolicos"}, {"label": "With hugs, caresses and frequent touch", "value": "conexao_fisica"}, {"label": "Dedicating exclusive quality time", "value": "presenca_ativa"}]'),
  (30, 'If you could ask for one thing to feel more loved, it would be:', '[{"label": "Hearing more often how important I am", "value": "expressao_verbal"}, {"label": "Receiving more help with daily tasks", "value": "cuidado_pratico"}, {"label": "Receiving more surprises and symbolic gestures", "value": "gestos_simbolicos"}, {"label": "More physical affection and closeness", "value": "conexao_fisica"}, {"label": "More quality time and full attention", "value": "presenca_ativa"}]')
) AS q(question_number, question_text, options)
WHERE t.type = 'linguagens_amor' AND t.language = 'en';

-- Insert new questions for Portuguese Portugal (pt-pt) test
INSERT INTO test_questions (test_id, question_number, question_text, options, language)
SELECT t.id, q.question_number, q.question_text, q.options::jsonb, 'pt-pt'
FROM tests t
CROSS JOIN (VALUES
  (1, 'Acabou de receber uma notícia difícil no trabalho. O que mais o(a) ajudaria?', '[{"label": "Alguém sentar-se ao seu lado em silêncio, apenas fazendo companhia", "value": "presenca_ativa"}, {"label": "Receber uma massagem nos ombros para aliviar a tensão", "value": "conexao_fisica"}, {"label": "Ouvir \"Eu acredito em ti, vais superar isto\"", "value": "expressao_verbal"}, {"label": "Alguém preparar um chá ou organizar algo para si", "value": "cuidado_pratico"}, {"label": "Receber uma mensagem ou cartão de apoio inesperado", "value": "gestos_simbolicos"}]'),
  (2, 'Após uma discussão com alguém próximo, o que o(a) faz sentir que a paz foi restaurada?', '[{"label": "A pessoa resolver algo que o(a) estava a incomodar", "value": "cuidado_pratico"}, {"label": "Um abraço demorado sem precisar de palavras", "value": "conexao_fisica"}, {"label": "Receber um pedido de desculpas sincero e elaborado", "value": "expressao_verbal"}, {"label": "A pessoa aparecer com algo especial para vocês dois", "value": "gestos_simbolicos"}, {"label": "Passarem tempo juntos a fazer algo relaxante", "value": "presenca_ativa"}]'),
  (3, 'Num dia de ansiedade, qual atitude de alguém querido o(a) acalmaria mais?', '[{"label": "Ficar de mãos dadas enquanto respira", "value": "conexao_fisica"}, {"label": "Dizer palavras tranquilizadoras com calma", "value": "expressao_verbal"}, {"label": "Trazer algo que gosta para o(a) distrair", "value": "gestos_simbolicos"}, {"label": "Tratar de alguma tarefa pendente para tirar da sua cabeça", "value": "cuidado_pratico"}, {"label": "Simplesmente ficar por perto, disponível", "value": "presenca_ativa"}]'),
  (4, 'Quando está doente, o que mais o(a) faz sentir cuidado(a)?', '[{"label": "Alguém passar o dia ao seu lado, mesmo sem fazer nada especial", "value": "presenca_ativa"}, {"label": "Ouvir mensagens de \"melhoras\" e preocupação genuína", "value": "expressao_verbal"}, {"label": "Receber um mimo especial como flores ou algo que adora", "value": "gestos_simbolicos"}, {"label": "Alguém preparar uma sopa ou organizar os seus medicamentos", "value": "cuidado_pratico"}, {"label": "Receber festas e carinho físico enquanto descansa", "value": "conexao_fisica"}]'),
  (5, 'Após um fracasso pessoal, qual reação o(a) faria sentir mais apoiado(a)?', '[{"label": "Alguém pesquisar soluções ou alternativas para si", "value": "cuidado_pratico"}, {"label": "Ouvir \"Isto não diminui quem és\"", "value": "expressao_verbal"}, {"label": "Receber uma prenda simbólica de encorajamento", "value": "gestos_simbolicos"}, {"label": "Um abraço forte e prolongado", "value": "conexao_fisica"}, {"label": "A pessoa reservar tempo para estar consigo", "value": "presenca_ativa"}]'),
  (6, 'Quando está a passar por luto ou perda, o que mais o(a) conforta?', '[{"label": "Alguém tratar de questões práticas que não consegue enfrentar", "value": "cuidado_pratico"}, {"label": "Presença silenciosa, apenas estando ali", "value": "presenca_ativa"}, {"label": "Toque gentil como segurar a sua mão ou abraço", "value": "conexao_fisica"}, {"label": "Palavras de conforto e memórias partilhadas", "value": "expressao_verbal"}, {"label": "Receber algo significativo em memória do momento", "value": "gestos_simbolicos"}]'),
  (7, 'Conseguiu uma promoção no trabalho. Qual reação o(a) deixaria mais feliz?', '[{"label": "A pessoa organizar uma celebração surpresa", "value": "gestos_simbolicos"}, {"label": "Ouvir um discurso sincero sobre o seu mérito", "value": "expressao_verbal"}, {"label": "Receber um abraço apertado e efusivo", "value": "conexao_fisica"}, {"label": "Alguém disponibilizar-se para celebrar como quiser", "value": "presenca_ativa"}, {"label": "A pessoa resolver algo prático para facilitar a sua nova rotina", "value": "cuidado_pratico"}]'),
  (8, 'No seu aniversário, o que o(a) faz sentir mais especial?', '[{"label": "Alguém dedicar o dia inteiro para estar consigo", "value": "presenca_ativa"}, {"label": "Receber uma prenda bem pensada que mostra atenção", "value": "gestos_simbolicos"}, {"label": "Ouvir declarações e agradecimentos sinceros", "value": "expressao_verbal"}, {"label": "Abraços, beijos e muito contacto físico", "value": "conexao_fisica"}, {"label": "Alguém preparar tudo para não se preocupar com nada", "value": "cuidado_pratico"}]'),
  (9, 'Ao completar um projeto importante, como prefere ser reconhecido(a)?', '[{"label": "Um elogio público ou privado detalhado", "value": "expressao_verbal"}, {"label": "Uma prenda ou símbolo do feito", "value": "gestos_simbolicos"}, {"label": "Um high-five, palmadinha nas costas ou abraço", "value": "conexao_fisica"}, {"label": "Alguém querer saber os detalhes e ouvir sobre a experiência", "value": "presenca_ativa"}, {"label": "Ajuda prática com o próximo passo", "value": "cuidado_pratico"}]'),
  (10, 'Numa conquista académica ou profissional, o que mais o(a) emociona?', '[{"label": "Alguém fazer algo especial para marcar o momento", "value": "gestos_simbolicos"}, {"label": "Ouvir o quanto estão orgulhosos de si", "value": "expressao_verbal"}, {"label": "Receber abraços calorosos de celebração", "value": "conexao_fisica"}, {"label": "A pessoa pausar tudo para celebrar consigo", "value": "presenca_ativa"}, {"label": "Ajuda para organizar a próxima fase", "value": "cuidado_pratico"}]'),
  (11, 'Quando atinge uma meta de fitness ou saúde, qual reação o(a) motiva mais?', '[{"label": "Alguém acompanhá-lo(a) nessa jornada", "value": "presenca_ativa"}, {"label": "Elogios específicos sobre o seu esforço e resultado", "value": "expressao_verbal"}, {"label": "Um mimo ou recompensa simbólica", "value": "gestos_simbolicos"}, {"label": "Massagem ou toque celebratório", "value": "conexao_fisica"}, {"label": "Ajuda para manter o novo hábito", "value": "cuidado_pratico"}]'),
  (12, 'Ao receber boas notícias inesperadas, o que mais quer?', '[{"label": "Partilhar a novidade com tempo e atenção de alguém", "value": "presenca_ativa"}, {"label": "Expressar a sua alegria em palavras com alguém", "value": "expressao_verbal"}, {"label": "Saltar, abraçar e expressar fisicamente", "value": "conexao_fisica"}, {"label": "Receber ou dar algo para marcar o momento", "value": "gestos_simbolicos"}, {"label": "Alguém ajudar a planear os próximos passos", "value": "cuidado_pratico"}]'),
  (13, 'Num domingo comum, o que o(a) faz sentir mais ligado(a) a alguém?', '[{"label": "Fazer tarefas domésticas juntos", "value": "cuidado_pratico"}, {"label": "Conversar profundamente sobre qualquer assunto", "value": "expressao_verbal"}, {"label": "Passar o dia lado a lado, mesmo em silêncio", "value": "presenca_ativa"}, {"label": "Trocar carinhos no sofá a ver algo", "value": "conexao_fisica"}, {"label": "Receber ou preparar algo especial para o outro", "value": "gestos_simbolicos"}]'),
  (14, 'Ao chegar do trabalho cansado(a), o que mais o(a) acolhe?', '[{"label": "Encontrar a casa arrumada ou o jantar pronto", "value": "cuidado_pratico"}, {"label": "Ouvir \"Como foi o teu dia?\" com interesse genuíno", "value": "expressao_verbal"}, {"label": "Um abraço demorado à porta", "value": "conexao_fisica"}, {"label": "Ter companhia enquanto descansa", "value": "presenca_ativa"}, {"label": "Uma pequena surpresa como um bilhete ou doce favorito", "value": "gestos_simbolicos"}]'),
  (15, 'Durante uma refeição em família, o que mais o(a) toca?', '[{"label": "Conversas animadas e ligação verbal", "value": "expressao_verbal"}, {"label": "Alguém ter preparado o seu prato favorito", "value": "cuidado_pratico"}, {"label": "Sentar-se próximo, com contacto físico casual", "value": "conexao_fisica"}, {"label": "Todos estarem presentes e focados", "value": "presenca_ativa"}, {"label": "Pequenos rituais como brindes ou tradições", "value": "gestos_simbolicos"}]'),
  (16, 'Numa viagem com alguém especial, o que torna a experiência memorável?', '[{"label": "Conversas profundas durante o trajeto", "value": "expressao_verbal"}, {"label": "Alguém tratar da logística e organização", "value": "cuidado_pratico"}, {"label": "Explorar lugares juntos, lado a lado", "value": "presenca_ativa"}, {"label": "Momentos de intimidade física", "value": "conexao_fisica"}, {"label": "Souvenirs e lembranças simbólicas", "value": "gestos_simbolicos"}]'),
  (17, 'No fim de um dia stressante, o que mais o(a) relaxa?', '[{"label": "Desabafar e ser ouvido(a) com atenção", "value": "expressao_verbal"}, {"label": "Alguém assumir as suas responsabilidades por uma noite", "value": "cuidado_pratico"}, {"label": "Receber carinho físico como massagem ou festas", "value": "conexao_fisica"}, {"label": "Companhia silenciosa e reconfortante", "value": "presenca_ativa"}, {"label": "Uma surpresa simples para alegrar", "value": "gestos_simbolicos"}]'),
  (18, 'Numa manhã de folga, o que o(a) faz sentir amado(a)?', '[{"label": "Pequeno-almoço na cama ou algo preparado com carinho", "value": "cuidado_pratico"}, {"label": "Acordar com beijos e abraços", "value": "conexao_fisica"}, {"label": "Ouvir \"Bom dia\" de forma carinhosa e atenciosa", "value": "expressao_verbal"}, {"label": "A pessoa querer passar a manhã ao seu lado", "value": "presenca_ativa"}, {"label": "Encontrar um bilhete ou pequena surpresa", "value": "gestos_simbolicos"}]'),
  (19, 'O que mais o(a) faz confiar que alguém o(a) ama?', '[{"label": "Declarações verbais frequentes de amor", "value": "expressao_verbal"}, {"label": "Ações práticas do dia a dia que facilitam a sua vida", "value": "cuidado_pratico"}, {"label": "Prendas e gestos simbólicos inesperados", "value": "gestos_simbolicos"}, {"label": "Toque frequente e busca por proximidade física", "value": "conexao_fisica"}, {"label": "Tempo de qualidade dedicado a si", "value": "presenca_ativa"}]'),
  (20, 'Num relacionamento de longa data, o que mantém a chama acesa?', '[{"label": "Surpresas românticas e gestos simbólicos", "value": "gestos_simbolicos"}, {"label": "Conversas profundas e ligação verbal", "value": "expressao_verbal"}, {"label": "Intimidade física e carinhos frequentes", "value": "conexao_fisica"}, {"label": "Momentos de presença plena juntos", "value": "presenca_ativa"}, {"label": "Cuidado mútuo nas pequenas coisas", "value": "cuidado_pratico"}]'),
  (21, 'Quando sente que está a distanciar-se de alguém, o que o(a) reaproxima?', '[{"label": "Uma conversa honesta sobre sentimentos", "value": "expressao_verbal"}, {"label": "Uma prenda ou gesto significativo de reconciliação", "value": "gestos_simbolicos"}, {"label": "Abraços e restauração do contacto físico", "value": "conexao_fisica"}, {"label": "Passarem tempo de qualidade juntos", "value": "presenca_ativa"}, {"label": "A pessoa tomar atitudes práticas para resolver problemas", "value": "cuidado_pratico"}]'),
  (22, 'O que o(a) faz sentir negligenciado(a) num relacionamento?', '[{"label": "Falta de palavras de afirmação e elogios", "value": "expressao_verbal"}, {"label": "Ausência de prendas ou gestos simbólicos", "value": "gestos_simbolicos"}, {"label": "Pouco contacto físico e intimidade", "value": "conexao_fisica"}, {"label": "A pessoa nunca ter tempo para si", "value": "presenca_ativa"}, {"label": "Não ajudar nas tarefas e responsabilidades", "value": "cuidado_pratico"}]'),
  (23, 'Numa amizade verdadeira, o que mais valoriza?', '[{"label": "Poder contar tudo e ser ouvido(a)", "value": "expressao_verbal"}, {"label": "Ajuda mútua em momentos práticos", "value": "cuidado_pratico"}, {"label": "Lembranças e gestos que mostram que pensam em si", "value": "gestos_simbolicos"}, {"label": "Abraços e demonstrações físicas de afeto", "value": "conexao_fisica"}, {"label": "Passarem tempo juntos regularmente", "value": "presenca_ativa"}]'),
  (24, 'Ao conhecer alguém novo, o que o(a) faz sentir ligação imediata?', '[{"label": "Conversa fluida e interessante", "value": "expressao_verbal"}, {"label": "A pessoa oferecer-se para ajudar em algo", "value": "cuidado_pratico"}, {"label": "Troca de pequenas gentilezas ou prendas", "value": "gestos_simbolicos"}, {"label": "Contacto físico natural como aperto de mão caloroso", "value": "conexao_fisica"}, {"label": "Vontade de passar mais tempo juntos", "value": "presenca_ativa"}]'),
  (25, 'Pensando na sua infância, quando se sentia mais amado(a)?', '[{"label": "Quando ouviam as suas histórias com atenção", "value": "presenca_ativa"}, {"label": "Quando recebia elogios e incentivo verbal", "value": "expressao_verbal"}, {"label": "Quando ganhava prendas significativas", "value": "gestos_simbolicos"}, {"label": "Quando alguém cuidava das suas necessidades práticas", "value": "cuidado_pratico"}, {"label": "Quando recebia abraços e carinho físico", "value": "conexao_fisica"}]'),
  (26, 'Com a sua família hoje, o que mais o(a) faz sentir pertença?', '[{"label": "Reuniões onde todos estão presentes", "value": "presenca_ativa"}, {"label": "Conversas e telefonemas frequentes", "value": "expressao_verbal"}, {"label": "Tradições e rituais familiares", "value": "gestos_simbolicos"}, {"label": "Apoio mútuo em questões práticas", "value": "cuidado_pratico"}, {"label": "Demonstrações físicas de afeto", "value": "conexao_fisica"}]'),
  (27, 'O que mais sente falta em relação à sua família quando está longe?', '[{"label": "Das conversas e da voz das pessoas", "value": "expressao_verbal"}, {"label": "Da ajuda prática e do suporte mútuo", "value": "cuidado_pratico"}, {"label": "Dos abraços e do contacto físico", "value": "conexao_fisica"}, {"label": "Das tradições e momentos especiais", "value": "gestos_simbolicos"}, {"label": "De simplesmente estar junto", "value": "presenca_ativa"}]'),
  (28, 'Qual memória afetiva familiar é mais forte para si?', '[{"label": "Palavras de encorajamento e amor", "value": "expressao_verbal"}, {"label": "Alguém a cuidar de si quando precisou", "value": "cuidado_pratico"}, {"label": "Prendas ou objetos que guarda até hoje", "value": "gestos_simbolicos"}, {"label": "Abraços e colo em momentos importantes", "value": "conexao_fisica"}, {"label": "Momentos de presença e atenção plena", "value": "presenca_ativa"}]'),
  (29, 'Como costuma demonstrar amor para pessoas importantes?', '[{"label": "Com palavras de afirmação e elogios", "value": "expressao_verbal"}, {"label": "Fazendo coisas práticas para facilitar a vida delas", "value": "cuidado_pratico"}, {"label": "Dando prendas pensadas e significativas", "value": "gestos_simbolicos"}, {"label": "Com abraços, carinhos e toque frequente", "value": "conexao_fisica"}, {"label": "Dedicando tempo de qualidade exclusivo", "value": "presenca_ativa"}]'),
  (30, 'Se pudesse pedir uma coisa para se sentir mais amado(a), seria:', '[{"label": "Ouvir mais frequentemente o quanto sou importante", "value": "expressao_verbal"}, {"label": "Receber mais ajuda nas tarefas do dia a dia", "value": "cuidado_pratico"}, {"label": "Receber mais surpresas e gestos simbólicos", "value": "gestos_simbolicos"}, {"label": "Mais carinho físico e proximidade", "value": "conexao_fisica"}, {"label": "Mais tempo de qualidade e atenção plena", "value": "presenca_ativa"}]')
) AS q(question_number, question_text, options)
WHERE t.type = 'linguagens_amor' AND t.language = 'pt-pt';

-- Update questions_count in tests table
UPDATE tests SET questions_count = 30 WHERE type = 'linguagens_amor';
