-- Update MBTI test metadata
UPDATE tests
SET 
  questions_count = 60,
  estimated_minutes = 15,
  description = 'Descubra como você percebe o mundo, toma decisões e se relaciona com a vida. Este teste identifica o seu tipo psicológico segundo a teoria dos tipos de Carl Jung e adapta-o à linguagem simbólica do Essentia.'
WHERE name = 'MBTI';

-- Delete existing MBTI questions
DELETE FROM test_questions 
WHERE test_id = (SELECT id FROM tests WHERE name = 'MBTI');

-- Insert MBTI questions (60 questions with Likert scale)
INSERT INTO test_questions (test_id, question_number, question_text, options) VALUES
((SELECT id FROM tests WHERE name = 'MBTI'), 1, 'Sinto-me energizado ao estar rodeado de pessoas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 2, 'Prefiro momentos de reflexão e silêncio para recarregar minhas energias.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"I"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 3, 'Gosto de conhecer novas pessoas e iniciar conversas espontaneamente.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 4, 'Costumo pensar antes de falar, avaliando bem o que direi.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"I"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 5, 'Sinto-me mais confortável em ambientes agitados e cheios de estímulos.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 6, 'Prefiro grupos pequenos ou situações em que posso me conectar profundamente.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"I"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 7, 'Quando chego a um evento, costumo chamar atenção naturalmente.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 8, 'Valorizo o tempo sozinho para processar minhas ideias.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"I"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 9, 'Sou mais falante e espontâneo do que reservado.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 10, 'Sinto-me drenado após muitas interações sociais seguidas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"I"}'::jsonb),

((SELECT id FROM tests WHERE name = 'MBTI'), 11, 'Foco mais no que é prático e real do que em ideias abstratas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"S"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 12, 'Gosto de imaginar possibilidades e cenários futuros.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"N"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 13, 'Confio mais no que posso observar e medir do que no que é intuitivo.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"S"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 14, 'Sou atraído por simbolismos e significados ocultos nas coisas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"N"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 15, 'Prefiro fatos concretos a hipóteses e suposições.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"S"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 16, 'Tenho facilidade em perceber padrões e conexões invisíveis.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"N"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 17, 'Sou detalhista e atento ao presente.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"S"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 18, 'Gosto de ideias ousadas, mesmo que pareçam distantes da realidade.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"N"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 19, 'Sigo instruções com precisão e foco no resultado.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"S"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 20, 'Sinto-me inspirado por sonhos, visões e inspirações criativas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"N"}'::jsonb),

((SELECT id FROM tests WHERE name = 'MBTI'), 21, 'Costumo tomar decisões com base na lógica e em critérios racionais.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"T"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 22, 'Considero o impacto emocional das minhas decisões sobre os outros.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 23, 'Gosto de analisar prós e contras antes de decidir.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"T"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 24, 'Dou prioridade à harmonia, mesmo que precise abrir mão de algo.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 25, 'Sou objetivo e direto ao lidar com problemas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"T"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 26, 'Procuro compreender os sentimentos alheios antes de reagir.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 27, 'Gosto de regras claras e decisões imparciais.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"T"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 28, 'Sinto-me desconfortável quando alguém é tratado de forma fria.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 29, 'Valorizo eficiência e resultados acima de emoções.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"T"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 30, 'Prefiro preservar relacionamentos a vencer discussões.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),

((SELECT id FROM tests WHERE name = 'MBTI'), 31, 'Gosto de planejar e cumprir prazos com antecedência.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 32, 'Sinto-me mais criativo quando posso improvisar e ser flexível.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 33, 'Tenho prazer em finalizar tarefas e riscar metas concluídas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 34, 'Prefiro deixar as possibilidades abertas até o último momento.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 35, 'Gosto de rotina e previsibilidade.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 36, 'Trabalho melhor sob liberdade e inspiração do momento.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 37, 'Sou mais produtivo quando sigo uma estrutura clara.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 38, 'Costumo decidir de forma espontânea e intuitiva.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 39, 'Prefiro concluir um projeto antes de iniciar outro.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 40, 'Gosto de adaptar meus planos conforme as circunstâncias.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb),

((SELECT id FROM tests WHERE name = 'MBTI'), 41, 'Sou sociável e gosto de interagir com desconhecidos.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 42, 'Prefiro observar e ouvir antes de me envolver em grupos.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"I"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 43, 'Aprecio detalhes concretos e informações verificáveis.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"S"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 44, 'Tenho facilidade em visualizar o que ainda não existe.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"N"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 45, 'Sou mais racional do que emotivo.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"T"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 46, 'Sou guiado mais pelo coração do que pela razão.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 47, 'Sinto satisfação em seguir regras e estruturas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 48, 'Prefiro deixar espaço para surpresas e improvisos.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 49, 'Gosto de me cercar de pessoas e novidades.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 50, 'Necessito de períodos de solidão para recarregar.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"I"}'::jsonb),

((SELECT id FROM tests WHERE name = 'MBTI'), 51, 'Valorizo o que é comprovado e funcional.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"S"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 52, 'Sou atraído por ideias originais e simbólicas.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"S-N","favors":"N"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 53, 'Tomo decisões analisando dados concretos.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"T"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 54, 'Prefiro decisões baseadas em empatia e valores.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 55, 'Organização e pontualidade são essenciais para mim.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 56, 'Sinto que a vida é mais bonita quando não está toda planejada.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 57, 'Sou direto e assertivo ao comunicar o que penso.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"E-I","favors":"E"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 58, 'Prefiro evitar conflitos e preservar a harmonia.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"T-F","favors":"F"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 59, 'Trabalho melhor em ambientes previsíveis e estruturados.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"J"}'::jsonb),
((SELECT id FROM tests WHERE name = 'MBTI'), 60, 'Tenho mais energia quando há liberdade para criar e explorar.', 
  '{"scale":[{"text":"Discordo totalmente","value":1},{"text":"Discordo","value":2},{"text":"Neutro","value":3},{"text":"Concordo","value":4},{"text":"Concordo totalmente","value":5}],"dimension":"J-P","favors":"P"}'::jsonb);